spring:
  datasource:
    url: jdbc:h2:mem:devops_platform;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  sql:
    init:
      mode: always

  application:
    name: devops-platform

server:
  port: 8081